# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# See : https://circleci.com/developer/orbs/orb/circleci/windows
orbs:
  win: circleci/windows@2.4.1

jobs:
  test-app:
     executor: win/default
     steps:
       - checkout
       - run: dotnet test

  build-app:
     executor: win/default
     steps:
       - checkout
       - run: dotnet build

workflows:
  main-workflow:
    jobs:
      - test-app
      - build-app
